version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
  frontend:
    build: ./src
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app
    depends_on:
      - backend